### PR TITLE
new ECC

### PR DESCRIPTION
**Pull request by kzoacn**

### CODE REVIEW

**Comment by wangxiao1254** [comment]
1. There should not be an OT test (or run.sh) in emp-tool.
2. Please also put IO from emp-ot pull request here.

Thanks,

**Comment by wangxiao1254** [comment]
Just a reminder that the code does pass the Travis test. See "continuous-integration/travis-ci/pr — The Travis CI build failed" above/below.

**Comment by kzoacn** [comment]
/home/travis/build/emp-toolkit/emp-tool/emp-tool/emp-tool.cpp:5:61: error: ‘nullptr’ was not declared in this scope
 emp::ProtocolExecution* emp::ProtocolExecution::prot_exec = nullptr;

The g++ version is 5.4.0 in Travis CI. They do not enable C++11 automatically

**Comment by wangxiao1254** [comment]
Everything works on the main branch. https://travis-ci.org/emp-toolkit/emp-tool/builds/526460818

**Comment by wangxiao1254** [comment]
This feature has been incorporated now.

**Pull request closed without merging**
