### PR TITLE
I've Added Support for Integers to and from Arbitrary Bits in Memory

### PR DESCRIPTION
**Pull request by isheff**
Hi Xiao,

It's Isaac from MPI-SWS. I found it useful for our project to be able to create integers directly from arbitrary sequences of bits (more than 64 or even 128 of them) in RAM, so I created a branch of emp-tool that allows for that. This means more constructors for Integer, an additional variant of Integer::reveal, and a couple of helper functions pertaining to bool arrays. They should not in any way interfere with any existing software, just add capabilities.

Hope you find this useful,
- Isaac

### CODE REVIEW

**Comment by wangxiao1254** [comment]
Thanks! It looks great! Some comments:
1. I'm not sure I understand the modification in test/gen_circuit.cpp. It seems that testMe contains 168 bits, but L40 only uses the first 32 bits. Maybe a better idea is to create a separate testing function (in parallel to sort() ) that demonstrates the use?
2. I feel like the use of struct (as in the test case) could be problematic in the long run. In particular, I'm not sure if there is any guarantee that the struct array will be continuous. Would it be possible that some compiler may choose to align them according to the word size?

**Comment by isheff** [comment]
1. I just wanted to see if I could read some bits in from something other than an integer. (notably, something for which the shift operator << is undefined). That change can be removed.
2. True, structs don't have to be continuous. Compilers add padding in various ways. The test case probably shouldn't use them like this.

**Comment by isheff** [comment]
Should now be fixed.

I also made Integers reverse the bits they ingest by default, so that big-endian memory representations would make sense in emp::Integer, which is effectively little-endian, so far as I can tell.

**Comment by wangxiao1254** [comment]
Thanks for your contribution! It is a very solid PR!

**Pull request merged**
