### PR TITLE
Sha3

### PR DESCRIPTION
**Pull request by isheff**
I added a SHA3 calculator, using the Keccak_f circuit. 

This involves 2 changes:

1. I made it so cmake will compile the keccak_f circuit to C code (which git will ignore), and then we can import it from there, so we don't have to read from storage at runtime.

2. I added sha3_256.hpp, which includes a sha3-256 implementation (out of circuit) built on OpenSSL, and a sha3-256 implementation built in circuit. The in-circuilt implementation is built in a class, so that objects can be instantiated to do some work ahead of time (e.g. build the BristolFashion circuit object). This allows each hash done with the same object to be faster.

When running tests in emp-tool, I'm not sure how to reveal bits correctly. It seems that this causes segfaults. However, by testing in the semi-honest framework, I was able to verify that these sha3 implementations agree on a variety of inputs.

### CODE REVIEW

**Comment by wangxiao1254** [comment]
I updated the test case. Essentially, you need to "setupplain". The segfault is because `reveal` is trying to access the protocol pointer, which is not really set up unless you call the corresponding function.

**Comment by wangxiao1254** [comment]
Let me know if you need to work on the test case any more and I will merge it after I heard from you :)

**Comment by isheff** [comment]
I have updated the test case so it now checks a hash, but I noted that now, I don't have to run 2 parties. The test finishes if I only launch ALICE, before launching BOB. Why is that?

**Comment by wangxiao1254** [comment]
This is the plain protocol, which means it is plaintext verification of the circuit. Everything is done in clear for ease of debugging. You can even delete `int port, party;` and `parse_party_and_port(argv, &party, &port);`.  To test a full protocol, that would be in other repos :)

**Comment by isheff** [comment]
no worries! go ahead and merge it then!

**Comment by wangxiao1254** [comment]
I made some minor change. I put the header to emp-tool.h so that it won't need to be included separately

**Pull request merged**
