### PR TITLE
Add automatic detection of RDSEED

### PR DESCRIPTION
**Pull request by weikengchen**
Automatically runs a program with RDSEED and detects whether we should change to the default random device.

Previously PR, #45, fails because `OPTION(USE_RANDOM_DEVICE "Option description" OFF)` is in the wrong position.

This is relevant to the issue #44.

### CODE REVIEW

**Comment by weikengchen** [comment]
Existing Travis CI result: https://travis-ci.org/weikengchen/emp-tool/jobs/378562151

Wait for this Travis CI.

**Comment by wangxiao1254** [comment]
Oh, this is interesting and nice! I think in this case maybe we can create a folder for all testing programs instead of writing to a temp file. I'm sure we will need more tests for other instruction support later :)

**Comment by wangxiao1254** [comment]
added `compiler_test` folder for this.

**Comment by weikengchen** [comment]
Agree. Will modify and make a separate PR.

**Comment by wangxiao1254** [comment]
Thanks!

**Pull request closed without merging**
